spring:
  security:
    user:
      name: root
      password: toor
  jpa:
    .database-platform: org.hibernate.dialect.MySQLDialect
    .show-sql: true
    .hibernate:
      .ddl-auto: none
  datasource:
    .url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/user_auth
    .username: root
    .password: toor
    .driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    
    
logging:
  level:
    org.springframework: ERROR
    org.springframework.boot: DEBUG
    com.NaSSIB: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log